### ISSUE TITLE
find a bug in SDK

### ISSUE THREAD

**Issue by jxq96** [HuobiRDCenter/huobi_Cpp#15]
In your WriteLog method, you call the fopen function while you don't call fclose function to close the FP and release the fd. The fd resourse will be exhausted after few hours.

**Comment by jsimmons089** [comment]
I ran into this same issue.  need to call fclose

**Comment by elena-yuan** [comment]
Thank you for your support and feedback ! It is our negligence ,we will fix it in the next release！
