### ISSUE TITLE
Decimal.h 一堆编译告警

### ISSUE THREAD

**Issue by gpmn** [HuobiRDCenter/huobi_Cpp#18]
https://github.com/HuobiRDCenter/huobi_Cpp/blob/49822bdf2b7c2a27ee304b456c799512d9faa11e/include/Huobi/Decimal.h#L36    

snprintf(buf, DECDOUBLE_String, "%g", DECDOUBLE_String, value);   
===>   
snprintf(buf, DECDOUBLE_String, "%g",  value);    

一堆编译告警

**Comment by normalzero** [comment]
我都没用Decimal  直接自己解析字符串 自己计算小数的有效位就可以了

**Comment by normalzero** [comment]
这玩意是从 亚马逊某项目里面扒过来的 用着很别扭 有Decimal的增强版本 没更新  还不如不用

**Comment by macomfan** [comment]
libdecnumber是gcc的，decimal.h这个只是封装了对libdecnumber的调用，确实里面有些小问题。设计sdk的时候考虑到量化交易用字符串不太方便，double精度又不太够，所以才引入libdecnumber
