### ISSUE TITLE
src/Logger.cpp   句柄用尽bug

### ISSUE THREAD

**Issue by xiongyang** [HuobiRDCenter/huobi_Cpp#19]
logger.cpp 23行
src/Logger.cpp 
应该是
  if(log_fp == NULL) log_fp = fopen(log_file_locate.c_str(), "a");
原代码会导致每记录一条logger 新开一个文件句柄. 最终导致句柄用尽,程序挂起.

**Comment by macomfan** [comment]
新版本改成了每次记录完log后会关闭句柄，虽然效率有些低，但是不会有资源泄漏了
