### ISSUE TITLE
need help--during make in examples, need pthread lib

### ISSUE THREAD

**Issue by lakeandhubo** [HuobiRDCenter/huobi_Cpp#2]
when i made the examples, it has errors, like this, please help me

thanks.

===log===============================
~/Downloads/huobi_Cpp-master/examples/GetCandlestickData/build$ make
[ 50%] Linking CXX executable GetCandlestickData
/usr/bin/ld: /usr/local/lib/libHuobiClient.a(WebSocketWatchDog.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/GetCandlestickData.dir/build.make:101: recipe for target 'GetCandlestickData' failed
make[2]: *** [GetCandlestickData] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/GetCandlestickData.dir/all' failed
make[1]: *** [CMakeFiles/GetCandlestickData.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lakeandhubo** [comment]
addition:
OS: ubuntu 18.04.1

and you need install z lib at the same time with 3rd lib, you can use the command below:
sudo apt-get install zlib1g-dev

**Comment by lansheng228** [comment]
Need to add a dependency on pthread in the CMakeLists.txt file. I have added and submitted. I also added zlib dependencies.
In addition, if you have a patch, you are welcome to submit a pull request.
We welcome the community to participate in the improvement of the project.
Thank you.
