### ISSUE TITLE
示例中的 SubscribeCandleStickEvent 不能成功运行

### ISSUE THREAD

**Issue by arthasyey** [HuobiRDCenter/huobi_Cpp#20]
其他的订阅的也不能成功运行。正在debug，还没发现。欢迎与我微信/电话联系讨论  18811341794

**Comment by arthasyey** [comment]
@huobiapi @peopleremote @eynzhang @lansheng228

**Comment by macomfan** [comment]
请问不能成功运行是指的什么，1. 编译是否成功，2. 是否可以正常执行，只是执行后没有反应，3. restful的request接口能调用成功吗

**Comment by arthasyey** [comment]
> 请问不能成功运行是指的什么，1. 编译是否成功，2. 是否可以正常执行，只是执行后没有反应，3. restful的request接口能调用成功吗

执行但是不能获得行情数据。Restful的可以，websocket的不行

**Comment by arthasyey** [comment]
> 请问不能成功运行是指的什么，1. 编译是否成功，2. 是否可以正常执行，只是执行后没有反应，3. restful的request接口能调用成功吗

你自己试试就知道了，也一样的。

**Comment by macomfan** [comment]
您好，试了一下，基于最新的master的代码，我这没有问题。您那Restful能正常工作，说明网络是通的，那么剩下的很有可能是libwebsocket库有点问题，推荐使用libwebsokcet 3.1 版本，之前的版本貌似也有人反映过websocket工作不正常。另外您还可以试一下非官方的docker编译环境，https://hub.docker.com/r/macomfan/huobi_cpp_sdk_env 这里面的libwebsocket是3.1版本的
