### ISSUE TITLE
Huobi::SubscriptionClientImpl::subscribeOrderUpdateV2  未定义

### ISSUE THREAD

**Issue by xiongyang** [HuobiRDCenter/huobi_Cpp#26]
多个例子链接都会遇到 Huobi::SubscriptionClientImpl::subscribeOrderUpdateV2  符号未定义错误.
例如 SubscribeMarketBBOEvent

[100%] Linking CXX executable SubscribeMarketBBOEvent
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libHuobiClient.a(SubscriptionClientImpl.cpp.o):(.rodata._ZTVN5Huobi22SubscriptionClientImplE[_ZTVN5Huobi22SubscriptionClientImplE]+0x78): undefined reference to `Huobi::SubscriptionClientImpl::subscribeOrderUpdateV2(char const*, std::function<void (Huobi::OrderUpdateV2Event const&)> const&, std::function<void (Huobi::HuobiApiException&)> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/SubscribeMarketBBOEvent.dir/build.make:112: SubscribeMarketBBOEvent] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/SubscribeMarketBBOEvent.dir/all] Error 2

**Comment by elena-yuan** [comment]
感谢反馈！已修复
