### ISSUE TITLE
如何支持代理，能否给出cpprest wss代理的示例

### ISSUE THREAD

**Issue by sylinuxhy** [HuobiRDCenter/huobi_Cpp#28]

**Comment by eynzhang** [comment]
@sylinuxhy ，感谢您的反馈，我们会在考虑在未来的版本中加入对代理的支持。
当前，您可以参考cpprest官方文档和代码
https://github.com/Microsoft/cpprestsdk/blob/master/Release/tests/functional/http/client/proxy_tests.cpp

**Comment by sylinuxhy** [comment]
感谢回复 已解决
