### ISSUE TITLE
wss api： TLS Short Read

### ISSUE THREAD

**Issue by sylinuxhy** [HuobiRDCenter/huobi_Cpp#29]
在香港阿里云上测试 wss接口 报错TLS Short Read，但是可以收到OrderUpdate Msg
在本地机器通过代理测试 wss接口 也是同样的错误，无法收到OrderUpdate Msg
请问这是什么原因？
以下是在阿里云测试输出日志
server response: {"action":"sub","code":200,"ch":"orders#eosusdt","data":{}}
server response: {"action":"ping","data":{"ts":1595578819682}}
{"action":"pong","data":{"ts":"1595578819682"}}
disconnection... 
exception Msg: TLS Short Read
server response: {"action":"req","code":200,"ch":"auth","data":{}}
server response: {"action":"sub","code":200,"ch":"orders#eosusdt","data":{}}
disconnection... 
exception Msg: TLS Short Read
server response: {"action":"req","code":200,"ch":"auth","data":{}}
server response: {"action":"sub","code":200,"ch":"orders#eosusdt","data":{}}
server response: {"action":"push","ch":"orders#eosusdt","data":{"lastActTime":1595578842727,"remainAmt":"5","orderId":62678599055412,"clientOrderId":"","eventType":"cancellation","orderStatus":"canceled","symbol":"eosusdt","type":"buy-limit"}}
eosusdt
server response: {"action":"push","ch":"orders#eosusdt","data":{"lastActTime":1595578843685,"remainAmt":"5","orderId":62678691348965,"clientOrderId":"","eventType":"cancellation","orderStatus":"canceled","symbol":"eosusdt","type":"buy-limit"}}
eosusdt
disconnection... 
exception Msg: TLS Short Read

**Comment by elena-yuan** [comment]
感谢您的使用和反馈，初步排查后推测问题是抛出异常时没有close 连接，已经修复，烦请验证是否解决问题

**Comment by sylinuxhy** [comment]
不是这个问题 TLS short read是你们在线程超时连接关闭了导致的， 原因如下： getCurrentTime（）返回的 int64，在线程外采用int 导致精度错误，见monitor超时判断函数

**Comment by elena-yuan** [comment]
感谢反馈
