### ISSUE TITLE
Any plan to support windows?

### ISSUE THREAD

**Issue by sawyer-chen** [HuobiRDCenter/huobi_Cpp#3]
I would like to use SDK on windows. Please hint me about Any part of code rely specially on linux? Maybe I can try to make it compatible on windows.

**Comment by lansheng228** [comment]
Hi：
I am using Qt to refactor the code. Qt is a cross-platform solution. 
If you have other methods, please feel free to submit pr.

**Comment by lansheng228** [comment]
The main libraries that the project depends on are: OpenSSL, curl, libwebsocket, zlib.
The compilation tool is cmake or gcc.
I am not sure if I can use these under Windows.
If you have experience in Windows development, welcome to improve this sdk.
We welcome the community to participate in the project.
If you have a patch, please submit a pull request.
Thank you.

**Comment by sawyer-chen** [comment]
Thank you for your reply. I'll try to compile the SDK under windows.
