### ISSUE TITLE
wss Market 接口报错：: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by sylinuxhy** [HuobiRDCenter/huobi_Cpp#30]
websocketMarketClient.cpp market（）函数如下代码块触发异常
string msg = client.receive().then([](websocket_incoming_message in_msg) {
                char buf[BUFF] = {0};
                unsigned int l = BUFF;
                in_msg.body().streambuf().getn((unsigned char *) buf, l);
                char sbuf[BUFF] = {0};
                gzDecompress(buf, in_msg.length(), sbuf, BUFF);
                return sbuf;
            }).get();
此处sbuf返回的是 正确的buff 但是，get()返回的对象转换成string报错 basic_string::_M_construct null not valid
测试机器 阿里云ubuntu16 
编译器版本gcc7.5 
第三方库版本 cpprest采用apt-get install安装

**Comment by elena-yuan** [comment]
感谢您的使用和反馈，该问题已经修复，烦请验证问题是否解决

**Comment by sylinuxhy** [comment]
改成 char* 没有修复 ，我通过string传参好像是可以的，没有详细查看 cpprest代码，
