### ISSUE TITLE
coredump for websocketMarketdemo

### ISSUE THREAD

**Issue by jcsfh** [HuobiRDCenter/huobi_Cpp#31]
Hello, I got core dump when try to run demo websocketMarketdemo:

![image](https://user-images.githubusercontent.com/14031676/89297212-14c33f80-d696-11ea-9e35-2c4a37a19c45.png)

Please take a look.

Thanks!

**Comment by eynzhang** [comment]
@jcsfh thanks for your feedback, this is fixed in latest master branch.
