### ISSUE TITLE
The server CPU is FULL

### ISSUE THREAD

**Issue by Eric-Sunjian** [HuobiRDCenter/huobi_Cpp#34]
I subscribed to two contracts using the subMBPrefresh interface, and the CPU exploded，please resolve it,thank you.

**Comment by elena-yuan** [comment]
We will try to fix it, cause it didn't happen in our machine ,but others have asked the same question, thanks for your feedback

**Comment by eynzhang** [comment]
@Eric-Sunjian We have to close this issue as there is no further update.
