### ISSUE TITLE
demo Aborted

### ISSUE THREAD

**Issue by Eric-Sunjian** [HuobiRDCenter/huobi_Cpp#35]
An error is reported after the demo has been running for a short time,maybe 1min or something.

websocketMarketdemo: /huobi/huobi_Cpp/include/rapidjson/document.h:1053: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
Aborted

**Comment by elena-yuan** [comment]
Do you still have the same problem? Have you tried debugging? It may appear when the returned value cannot be parsed.

**Comment by eynzhang** [comment]
@Eric-Sunjian we have to close this as there is no further update.
