### ISSUE TITLE
Websocket client is being destroyed

### ISSUE THREAD

**Issue by ForeverZyh** [HuobiRDCenter/huobi_Cpp#36]
```
client.subDepth(symbol, "step5", [](Depth depth) {
	cout << "subDepth" << endl;
	cout << depth.ts << endl;
	cout << depth.asks[0].price << endl;
  });
```  
https://github.com/HuobiRDCenter/huobi_Cpp/blob/master/src/client/websocketMarketClient.cpp
After running for 3-4 minutes, the code captures an exception: "Websocket client is being destroyed" in Lines 39-43.

**Comment by ForeverZyh** [comment]
https://github.com/HuobiRDCenter/huobi_Cpp/blob/3cf543d47caded33d92fae85e1746769a9efbdad/src/websocketHelper.cpp#L12
I think the pong message should contain a long value, not a string? 
Any ideas?

**Comment by elena-yuan** [comment]
For your first issue, i test it in my machine, but didn't have the same problem.
And i will keep tracking the problem like it ,thank you for your feedback!

**Comment by elena-yuan** [comment]
> https://github.com/HuobiRDCenter/huobi_Cpp/blob/3cf543d47caded33d92fae85e1746769a9efbdad/src/websocketHelper.cpp#L12
> 
> 
> I think the pong message should contain a long value, not a string?
> Any ideas?
it has been fixed by your  prompt, thanks a lot!
